<?php

ini_set("session.use_only_cookies", 1); // this line is used to set the session.use_only_cookies directive to 1, which means that the session id is only stored in the cookie and not in the URL. 
//This is important because storing the session id in the URL can make it vulnerable to session fixation attacks.
ini_set("session.use_strict_mode", 1); // this line is used to set the session.use_strict_mode directive to 1, which means that the website only uses session ids that are generated by the server.

session_set_cookie_params(["lifetime" => 1800, "domain" => "localhost", 
"path" => "/", "secure" => true, 
"httponly" => true]); // this line is used to set the session cookie parameters.


session_start(); // this line is used to start the session meaning


if(isset($_SESSION["user_id"])){

    if (!isset($_SESSION['last_regeneration'])){
        session_regenerate_id_loggedin();
        $_SESSION['last_regeneration'] = time();
        
    }else{
        $interval = 60*30; //30 minutes
    
        if  (time()- $_SESSION['last_regeneration'] >= $interval){
            session_regenerate_id_loggedin();
            $_SESSION['last_regeneration'] = time();
        }
    
    }
}
else{

    if (!isset($_SESSION['last_regeneration'])){
        session_regenerate_id();
        $_SESSION['last_regeneration'] = time();
        
    }else{
        $interval = 60*30; //30 minutes
    
        if  (time()- $_SESSION['last_regeneration'] >= $interval){
            session_regenerate_id();
            $_SESSION['last_regeneration'] = time();
        }
    
    }
}
function session_regenerate_id_loggedin(){
    session_regenerate_id(true); //this will regenerate the session id and delete the old session id
    $userId = $_SESSION["user_id"];
    $newSessionId = session_create_id(); //this will create an entire new id not regenerate exisiting id
    $sessionId = $newSessionId . "_" . $userId; //this will create a new session id by appending the user id to the new session id
    session_id($sessionId); //this will set the session id to the new session id    
    
}